name = "MoireIVC"
uuid = "90551720-b59b-4cf5-9c28-9970b3de4863"
authors = ["Bo Zou <zou.bo.phys@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
